version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: miamente
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - miamente_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    networks:
      - miamente_network
    depends_on:
      - db

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/miamente
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - miamente_network

  frontend:
    build: ./apps/web
    container_name: frontend
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - miamente_network

volumes:
  db_data:

networks:
  miamente_network:
    driver: bridge
