import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import "./globals.css";
import { Footer } from "@/components/footer";
import { HeaderWrapper as Header } from "@/components/header/header-wrapper";
import { ThemeProvider } from "@/components/theme-provider";
import { TooltipProvider } from "@/components/ui/tooltip";
import { AuthProvider } from "@/contexts/AuthContext";

const montserrat = Montserrat({ variable: "--font-montserrat", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${montserrat.variable} min-h-screen bg-white font-sans text-neutral-900 antialiased dark:bg-neutral-950 dark:text-neutral-50`}
        suppressHydrationWarning={true}
      >
        <ThemeProvider>
          <TooltipProvider>
            <AuthProvider>
              <Header />
              <main className="mx-auto min-h-[70vh] max-w-6xl px-4 py-8">{children}</main>
              <Footer />
            </AuthProvider>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
