import { render, screen } from "@testing-library/react";
import { describe, it, expect, vi } from "vitest";
import { ReactNode } from "react";

import RootLayout, { metadata } from "../layout";

// Mock Next.js font
vi.mock("next/font/google", () => ({
  Montserrat: vi.fn(() => ({
    variable: "--font-montserrat",
  })),
}));

// Mock all the providers and components
vi.mock("@/components/footer", () => ({
  Footer: () => <footer data-testid="footer">Footer</footer>,
}));

vi.mock("@/components/header/header-wrapper", () => ({
  HeaderWrapper: () => <header data-testid="header">Header</header>,
}));

vi.mock("@/components/theme-provider", () => ({
  ThemeProvider: ({ children }: { children: ReactNode }) => (
    <div data-testid="theme-provider">{children}</div>
  ),
}));

vi.mock("@/components/ui/tooltip", () => ({
  TooltipProvider: ({ children }: { children: ReactNode }) => (
    <div data-testid="tooltip-provider">{children}</div>
  ),
}));

vi.mock("@/contexts/AuthContext", () => ({
  AuthProvider: ({ children }: { children: ReactNode }) => (
    <div data-testid="auth-provider">{children}</div>
  ),
}));

describe("RootLayout", () => {
  it("should render all layout components", () => {
    render(
      <RootLayout>
        <div data-testid="child-content">Child content</div>
      </RootLayout>,
    );

    // Check that the main layout components are rendered
    expect(screen.getByTestId("theme-provider")).toBeInTheDocument();
    expect(screen.getByTestId("tooltip-provider")).toBeInTheDocument();
    expect(screen.getByTestId("auth-provider")).toBeInTheDocument();
    expect(screen.getByTestId("header")).toBeInTheDocument();
    expect(screen.getByTestId("footer")).toBeInTheDocument();
    expect(screen.getByTestId("child-content")).toBeInTheDocument();
  });

  it("should render children in main element", () => {
    render(
      <RootLayout>
        <div data-testid="page-content">Page content</div>
      </RootLayout>,
    );

    const main = screen.getByRole("main");
    expect(main).toBeInTheDocument();
    expect(main).toContainElement(screen.getByTestId("page-content"));
  });

  it("should have correct HTML structure", () => {
    render(
      <RootLayout>
        <div>Content</div>
      </RootLayout>,
    );

    const html = document.documentElement;
    expect(html).toHaveAttribute("lang", "es");

    const body = document.body;
    expect(body).toHaveClass("min-h-screen");
    expect(body).toHaveClass("bg-white");
    expect(body).toHaveClass("font-sans");
    expect(body).toHaveClass("text-neutral-900");
    expect(body).toHaveClass("antialiased");
    expect(body).toHaveClass("dark:bg-neutral-950");
    expect(body).toHaveClass("dark:text-neutral-50");
  });

  it("should have suppressHydrationWarning on body", () => {
    // This is a React prop that doesn't appear as an HTML attribute
    // We'll just verify the component renders without hydration warnings
    const { container } = render(
      <RootLayout>
        <div>Content</div>
      </RootLayout>,
    );

    const body = document.body;
    expect(body).toBeInTheDocument();
    expect(container).toBeInTheDocument();
  });

  it("should include Montserrat font variable", () => {
    render(
      <RootLayout>
        <div>Content</div>
      </RootLayout>,
    );

    const body = document.body;
    expect(body.className).toContain("--font-montserrat");
  });

  it("should have correct main element classes", () => {
    render(
      <RootLayout>
        <div>Content</div>
      </RootLayout>,
    );

    const main = screen.getByRole("main");
    expect(main).toHaveClass("mx-auto");
    expect(main).toHaveClass("min-h-[70vh]");
    expect(main).toHaveClass("max-w-6xl");
    expect(main).toHaveClass("px-4");
    expect(main).toHaveClass("py-8");
  });

  it("should render providers in correct nesting order", () => {
    render(
      <RootLayout>
        <div data-testid="test-content">Test</div>
      </RootLayout>,
    );

    // Check nesting order: ThemeProvider > TooltipProvider > AuthProvider
    const themeProvider = screen.getByTestId("theme-provider");
    const tooltipProvider = screen.getByTestId("tooltip-provider");
    const authProvider = screen.getByTestId("auth-provider");

    expect(themeProvider).toContainElement(tooltipProvider);
    expect(tooltipProvider).toContainElement(authProvider);
    expect(authProvider).toContainElement(screen.getByTestId("header"));
    expect(authProvider).toContainElement(screen.getByTestId("footer"));
  });
});

describe("metadata", () => {
  it("should export correct metadata", () => {
    expect(metadata).toBeDefined();
    expect(metadata.title).toBe("Create Next App");
    expect(metadata.description).toBe("Generated by create next app");
  });

  it("should have title and description properties", () => {
    expect(metadata).toHaveProperty("title");
    expect(metadata).toHaveProperty("description");
    expect(typeof metadata.title).toBe("string");
    expect(typeof metadata.description).toBe("string");
  });
});
