"""refactor_is_default_specialty_to_boolean

Revision ID: 0d123c99e3cb
Revises: 2aa134a19798
Create Date: 2025-09-12 21:58:20.752890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d123c99e3cb'
down_revision = '2aa134a19798'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
