"""Fix professional specialties is_active column type

Revision ID: 2aa134a19798
Revises: 93b9371ec3e1
Create Date: 2025-09-12 17:19:50.729951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa134a19798'
down_revision = '93b9371ec3e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE professional_specialties ALTER COLUMN is_active TYPE BOOLEAN USING is_active::boolean")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('professional_specialties', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
