"""remove_certifications_field

Revision ID: 37079caf8c05
Revises: 73768d084541
Create Date: 2025-09-12 22:24:03.426701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37079caf8c05'
down_revision = '73768d084541'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professionals', 'certifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professionals', sa.Column('certifications', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
