"""add_is_default_column_and_remove_old

Revision ID: 73768d084541
Revises: 0d123c99e3cb
Create Date: 2025-09-12 22:05:09.224023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73768d084541'
down_revision = '0d123c99e3cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the new column as nullable first
    op.add_column('professional_specialties', sa.Column('is_default', sa.Boolean(), nullable=True))
    
    # Update existing data: set is_default to True where is_default_specialty was not null
    op.execute("UPDATE professional_specialties SET is_default = (is_default_specialty IS NOT NULL)")
    
    # Now make the column NOT NULL
    op.alter_column('professional_specialties', 'is_default', nullable=False)
    
    # Drop the old column
    op.drop_column('professional_specialties', 'is_default_specialty')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional_specialties', sa.Column('is_default_specialty', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('professional_specialties', 'is_default')
    # ### end Alembic commands ###
