"""Add professional specialties table

Revision ID: 93b9371ec3e1
Revises: 79edc6788fbd
Create Date: 2025-09-12 17:16:38.013245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b9371ec3e1'
down_revision = '79edc6788fbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
