"""restore_certifications_field

Revision ID: b99e5b6a4145
Revises: 37079caf8c05
Create Date: 2025-09-12 22:28:47.781431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99e5b6a4145'
down_revision = '37079caf8c05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professionals', sa.Column('certifications', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professionals', 'certifications')
    # ### end Alembic commands ###
