name: Setup Python Backend
description: Set up Python and install backend dev dependencies
inputs:
  python-version:
    description: Python version
    default: '3.13'
  working-directory:
    description: Project path
    default: backend
  extra-packages:
    description: Extra pip packages (space-separated)
    default: ''
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: ${{ inputs.working-directory }}/pyproject.toml

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]"
        if [ -n "${{ inputs.extra-packages }}" ]; then
          pip install ${{ inputs.extra-packages }}
        fi
