name: Backend CI

on:
  pull_request:
    branches: [develop]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

defaults:
  run:
    working-directory: backend

jobs:
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python & deps
        uses: ./.github/actions/setup-backend
        with:
          python-version: "3.13"

      - name: Run Black (Formatter)
        run: black app --check

      - name: Run Pylint (Linter)
        run: pylint app --output-format=text --fail-under=9 > pylint-report.txt || true

      - name: Run Flake8 (Linter)
        run: flake8 app --output-file=flake8-report.txt || true

      - name: Upload Lint Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-reports
          path: |
            backend/flake8-report.txt
            backend/pylint-report.txt

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python & deps
        uses: ./.github/actions/setup-backend
        with:
          python-version: "3.13"

      - name: Run Unit Tests with pytest and Coverage
        run: |
          pytest \
            --ignore=tests/integration \
            --cov=app \
            --cov-report=xml:unit_coverage.xml \
            --cov-report=html \
            --html=unit_report.html \
            --self-contained-html

      - name: Upload Test Reports Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-reports
          path: |
            backend/unit_report.html
            backend/unit_coverage.xml

  docker-build-validate:
    name: Docker build (validate, no push)
    runs-on: ubuntu-latest
    needs: [lint,unit-tests]
    steps:
      - uses: actions/checkout@v4

      - name: Build image (no push)
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          load: false
          tags: ${{ secrets.DOCKERHUB_BACKEND_REPOSITORY }}:${{ github.sha }}

  sonar:
    name: SonarCloud (aggregate coverage)
    runs-on: ubuntu-latest
    needs:
      - docker-build-validate
    steps:
      - uses: actions/checkout@v4

      - name: Download lint artifacts
        uses: actions/download-artifact@v4
        with:
          name: lint-reports
          path: artifacts-downloaded

      - name: Download unit artifacts
        uses: actions/download-artifact@v4
        with:
          name: unit-test-reports
          path: artifacts-downloaded

      - name: SonarCloud Scan (Backend)
        uses: SonarSource/sonarqube-scan-action@v5.3.1
        with:
          projectBaseDir: backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
